<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SanSamplePagination\Module'                           => __DIR__ . '/Module.php',
    'SanSamplePagination\Controller\TablesampleController' => __DIR__ . '/src/SanSamplePagination/Controller/TablesampleController.php',
    'SanSamplePagination\Form\SampleForm'                  => __DIR__ . '/src/SanSamplePagination/Form/SampleForm.php',
    'SanSamplePagination\Model\Sample'                     => __DIR__ . '/src/SanSamplePagination/Model/Sample.php',
    'SanSamplePagination\Model\SampleTable'                => __DIR__ . '/src/SanSamplePagination/Model/SampleTable.php',
);