<?php
$title = 'Edit Sample';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'SanSamplePagination/sample-id',
    array(
        'action'     => 'edit',
        'id'         => $this->id,
        'controller' => 'tablesample'
    )
));
$form->prepare();

echo $this->form()->openTag($form);
/*echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('gender'));*/

echo $this->formCollection($form); 

//echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();